### ISSUE TITLE
Not opened website

### ISSUE THREAD

**Issue by DmytroLitvinov** [oskaerik/theevalgame#1]
Website can't be opened.

<img width="1350" alt="image" src="https://github.com/oskaerik/theevalgame/assets/16066485/84e7f265-ebdd-4385-9aaf-6e8d6dc071fc">

Issue in console:
> future: <PyodideTask finished name='Task-10' coro=<PyodideConnection.receive_loop() done, defined at /lib/python3.11/site-packages/flet/pyodide_connection.py:42> exception=TypeError("RegisterWebClientRequestPayload.__init__() missing 1 required positional argument: 'media'")>

**Comment by oskaerik** [comment]
Thanks for making me aware! Fixed now 😊
